# Generated by Django 4.1.2 on 2022-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('judge', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'whale',
                'managed': False,
            },
        ),
    ]
