# Generated by Django 4.1.2 on 2022-11-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Whale', # モデル名
            old_name='judge',   # 変更前
            new_name='move'    # 変更後
        )
    ]
