# Generated by Django 4.1.2 on 2022-12-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0002_auto_20221111_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='EX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exchange_adress_tabel',
                'managed': False,
            },
        ),
    ]
